---
- name: Deploy Microservice to GCP Artifact Registry
  hosts: localhost
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: Ensure required packages are installed
      package:
        name: [git, zip]
        state: present

    - name: Clone the React repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: Fail if service_name is not provided
      fail:
        msg: "Please provide the service_name using -e 'service_name=servicename'"
      when: service_name is not defined

    - name: Set working directory for the service
      set_fact:
        service_dir: "{{ project_path }}/src/{{ service_name }}"
        full_image_name: "{{ gcp_region }}-docker.pkg.dev/{{ gcp_project_id }}/{{ repo_name }}/{{ service_name }}:{{ image_tag }}"

    - name: Check if service directory exists
      stat:
        path: "{{ service_dir }}"
      register: service_dir_stat

    - name: Fail if service directory does not exist
      fail:
        msg: "Service directory {{ service_dir }} not found!"
      when: not service_dir_stat.stat.exists

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ full_image_name }}"
        source: build
        build:
         path: "{{ service_dir }}"
        push: false
   
    - name: Deploy GCP auth script from template
      template:
       src: gcp_auth.sh.j2
       dest: gcp_auth.sh
       mode: '0755'

    - name: Authenticate with GCP Artifact Registry
      shell: |
         ./gcp_auth.sh
      args:
       executable: /bin/bash

    - name: Push Docker image to Artifact Registry
      shell: |
        docker push {{ full_image_name }}
    
    - name: Make script executable
      file:
       path: render.sh.j2
       mode: '0755'
    
    - name: Render Kubernetes Manifests
      shell: |
          ./render.sh.j2
      args: 
        executable: /bin/bash

    - name: Deploy kubernetes 
      shell: |
            kubectl apply -f rendered_namespace.yaml
            kubectl apply -f rendered_manifest.yaml
            kubectl apply -f rendered_hpa.yaml
