---
- name: Build & Deploy Wanderlust-Mega-Project Frontend 
  hosts: localhost
  become: yes

  vars:
    repo_url: https://github.com/ray6811/Wanderlust-Mega-Project.git
    project_path: /opt
    
  tasks:
    - name: Clone the React repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: Install frontend dependencies
      shell: |
        source /home/jenkins/.nvm/nvm.sh
        cd {{ project_path }}/frontend
        npm install
      args:
        executable: /bin/bash
      become: yes

      

    - name: Build 
      shell: |
        source /home/jenkins/.nvm/nvm.sh
        cd {{ project_path }}/frontend
        npm run build
      args:
        executable: /bin/bash
      become: yes

    - name: Dployment on Server 
      copy:
        src: "{{ project_path }}/frontend/build/"
        dest: /var/www/
        owner: www-data
        group: www-data
        mode: '0755'
      become: yes

    

    
