---
- name: Build & Deploy Wanderlust-Mega-Project Frontend 
  hosts: localhost
  become: yes 

  vars:
    repo_url: https://github.com/ray6811/Wanderlust-Mega-Project.git
    project_path: /opt/
    
  tasks:
    - name: Clone the React repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: Install dependencies
      command: npm install
      args:
        chdir: "{{ project_path }}/frontend"

    - name: Build React app
      command: npm run build
      args:
        chdir: "{{ project_path }}/frontend"

    

    
